version: '3.1'
services:
  api-ts:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
  mongo:
    image: mongo:4.4.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
